const words = [
    { "word": "apple", "hint": "A round fruit with red or green skin" },
    { "word": "banana", "hint": "A long yellow fruit" },
    { "word": "grape", "hint": "A small round fruit, often purple or green" },
    { "word": "orange", "hint": "A citrus fruit with a tough bright reddish-yellow rind" },
    { "word": "watermelon", "hint": "A large, green-skinned fruit with sweet, red flesh" },
    { "word": "computer", "hint": "An electronic device for storing and processing data" },
    { "word": "television", "hint": "An electronic device for viewing moving images" },
    { "word": "refrigerator", "hint": "An appliance used to keep food cold" },
    { "word": "microwave", "hint": "An appliance used to heat food quickly" },
    { "word": "bicycle", "hint": "A two-wheeled vehicle powered by pedaling" },
    { "word": "airplane", "hint": "A powered flying vehicle with wings" },
    { "word": "train", "hint": "A series of connected vehicles traveling on railways" },
    { "word": "guitar", "hint": "A stringed musical instrument played with fingers or a pick" },
    { "word": "piano", "hint": "A large keyboard musical instrument" },
    { "word": "violin", "hint": "A stringed instrument played with a bow" },
    { "word": "drums", "hint": "A percussion instrument played by striking with sticks or hands" },
    { "word": "chocolate", "hint": "A sweet food made from cacao beans" },
    { "word": "icecream", "hint": "A frozen dessert made from cream and sugar" },
    { "word": "cookie", "hint": "A small, sweet baked treat" },
    { "word": "bread", "hint": "A staple food made from flour and water" },
    { "word": "hamburger", "hint": "A sandwich consisting of a cooked patty of ground meat" },
    { "word": "pizza", "hint": "A dish of Italian origin with a flat round base of dough topped with cheese and tomatoes" },
    { "word": "pasta", "hint": "An Italian dish made from dough and typically served with sauce" },
    { "word": "robot", "hint": "A machine capable of carrying out complex tasks automatically" },
    { "word": "unicorn", "hint": "A mythical animal typically represented as a horse with a single straight horn" },
    { "word": "dragon", "hint": "A mythical monster resembling a giant reptile" },
    { "word": "vampire", "hint": "A mythical creature that drinks blood" },
    { "word": "zombie", "hint": "A reanimated corpse in horror stories" },
    { "word": "alien", "hint": "A creature from another planet" },
    { "word": "ghost", "hint": "A spirit of a dead person" },
    { "word": "witch", "hint": "A woman thought to have magical powers" },
    { "word": "wizard", "hint": "A man who has magical powers" },
    { "word": "jungle", "hint": "A dense forest in a tropical region" },
    { "word": "desert", "hint": "A barren area of landscape with little rainfall" },
    { "word": "mountain", "hint": "A large natural elevation of the earth's surface" },
    { "word": "ocean", "hint": "A vast body of salt water covering most of the earth" },
    { "word": "river", "hint": "A large natural stream of water flowing in a channel" },
    { "word": "lake", "hint": "A large body of water surrounded by land" },
    { "word": "island", "hint": "A piece of land surrounded by water" },
    { "word": "volcano", "hint": "A mountain that erupts with lava" },
    { "word": "earthquake", "hint": "A sudden and violent shaking of the ground" },
    { "word": "tsunami", "hint": "A long high sea wave caused by an earthquake" },
    { "word": "hurricane", "hint": "A storm with violent wind, especially in the Caribbean" },
    { "word": "tornado", "hint": "A mobile, destructive vortex of violently rotating winds" },
    { "word": "rainbow", "hint": "A multicolored arc in the sky caused by refraction of light" },
    { "word": "lightning", "hint": "A sudden flash of light in the sky during a storm" },
    { "word": "thunder", "hint": "The sound caused by lightning" },
    { "word": "snowflake", "hint": "A single ice crystal that falls as snow" },
    { "word": "sunshine", "hint": "Direct sunlight unbroken by cloud" },
    { "word": "moonlight", "hint": "The light of the moon" },
    { "word": "dog", "hint": "A common pet known for barking" },
    { "word": "cat", "hint": "A common pet known for meowing" },
    { "word": "lion", "hint": "A large wild cat known as the king of the jungle" },
    { "word": "tiger", "hint": "A large wild cat with stripes" },
    { "word": "elephant", "hint": "The largest land animal with a trunk" },
    { "word": "giraffe", "hint": "A tall animal with a long neck" },
    { "word": "dolphin", "hint": "A smart marine mammal known for its playful nature" },
    { "word": "whale", "hint": "The largest marine mammal" },
    { "word": "shark", "hint": "A predatory fish with sharp teeth" },
    { "word": "octopus", "hint": "A marine animal with eight arms" },
    { "word": "penguin", "hint": "A flightless bird that lives in cold regions" },
    { "word": "eagle", "hint": "A large bird of prey with a hooked beak" },
    { "word": "sparrow", "hint": "A small, common songbird" },
    { "word": "ostrich", "hint": "The largest flightless bird" },
    { "word": "peacock", "hint": "A bird known for its colorful tail feathers" },
    { "word": "koala", "hint": "A marsupial that lives in eucalyptus trees" },
    { "word": "kangaroo", "hint": "A marsupial known for its hopping" },
    { "word": "panda", "hint": "A bear-like animal known for its black and white fur" },
    { "word": "zebra", "hint": "An African animal with black and white stripes" },
    { "word": "monkey", "hint": "A primate known for its agility and playfulness" },
    { "word": "chimpanzee", "hint": "A primate closely related to humans" },
    { "word": "rhinoceros", "hint": "A large animal with one or two horns on its nose" },
    { "word": "hippopotamus", "hint": "A large, mostly aquatic mammal" },
    { "word": "bear", "hint": "A large, heavy mammal with thick fur" },
    { "word": "wolf", "hint": "A wild carnivorous mammal related to dogs" },
    { "word": "fox", "hint": "A small, wild carnivorous mammal with a bushy tail" },
    { "word": "deer", "hint": "A herbivorous mammal with antlers" },
    { "word": "rabbit", "hint": "A small mammal with long ears and a short tail" },
    { "word": "squirrel", "hint": "A small rodent with a bushy tail" },
    { "word": "mouse", "hint": "A small rodent with a pointed nose" },
    { "word": "rat", "hint": "A larger rodent often found in urban areas" },
    { "word": "frog", "hint": "An amphibian with long legs for jumping" },
    { "word": "toad", "hint": "An amphibian similar to a frog but with drier skin" },
    { "word": "lizard", "hint": "A reptile with a long body and tail" },
    { "word": "snake", "hint": "A legless reptile that slithers" },
    { "word": "turtle", "hint": "A reptile with a hard shell" },
    { "word": "crocodile", "hint": "A large reptile with a long snout" },
    { "word": "alligator", "hint": "A large reptile similar to a crocodile but with a broader snout" },
    { "word": "butterfly", "hint": "An insect with colorful wings" },
    { "word": "bee", "hint": "An insect known for producing honey" },
    { "word": "ant", "hint": "A small insect that lives in colonies" },
    { "word": "spider", "hint": "An arachnid known for spinning webs" },
    { "word": "scorpion", "hint": "An arachnid with a stinger on its tail" },
    { "word": "fish", "hint": "An aquatic animal with gills" },
    { "word": "goldfish", "hint": "A small, orange aquarium fish" },
    { "word": "parrot", "hint": "A colorful bird known for mimicking sounds" },
    { "word": "hamster", "hint": "A small, furry rodent often kept as a pet" },
    { "word": "gerbil", "hint": "A small rodent similar to a hamster" },
    { "word": "hedgehog", "hint": "A small mammal with spiny back" },
    { "word": "porcupine", "hint": "A mammal with sharp quills" },
    { "word": "bat", "hint": "A nocturnal flying mammal" },
    { "word": "owl", "hint": "A nocturnal bird of prey with large eyes" },
    { "word": "flamingo", "hint": "A wading bird with pink feathers" },
    { "word": "cheetah", "hint": "The fastest land animal" },
    { "word": "leopard", "hint": "A large wild cat with a spotted coat" },
    { "word": "jaguar", "hint": "A large wild cat found in the Americas" },
    { "word": "lynx", "hint": "A medium-sized wild cat with tufted ears" },
    { "word": "cougar", "hint": "A large wild cat also known as a mountain lion" },
    { "word": "camel", "hint": "A desert animal with humps" },
    { "word": "donkey", "hint": "A domesticated animal related to horses" },
    { "word": "horse", "hint": "A large domesticated mammal used for riding" },
    { "word": "cow", "hint": "A domesticated animal raised for milk and meat" },
    { "word": "sheep", "hint": "A domesticated animal raised for wool" },
    { "word": "goat", "hint": "A domesticated animal with horns and a beard" },
    { "word": "pig", "hint": "A domesticated animal raised for pork" },
    { "word": "chicken", "hint": "A domesticated bird raised for eggs and meat" },
    { "word": "duck", "hint": "A waterfowl with a broad bill" },
    { "word": "goose", "hint": "A waterfowl larger than a duck" },
    { "word": "turkey", "hint": "A large bird native to North America" },
    { "word": "peafowl", "hint": "A bird known for its colorful tail feathers" },
    { "word": "ostrich", "hint": "The largest flightless bird" },
    { "word": "emu", "hint": "A large flightless bird native to Australia" },
    { "word": "kiwi", "hint": "A small flightless bird from New Zealand" },
    { "word": "woodpecker", "hint": "A bird known for pecking at wood" },
    { "word": "sparrow", "hint": "A small, common songbird" },
    { "word": "robin", "hint": "A bird with a red breast" },
    { "word": "swallow", "hint": "A bird known for its swift flight" },
    { "word": "seagull", "hint": "A bird commonly found near the sea" },
    { "word": "albatross", "hint": "A large seabird with long wings" },
    { "word": "pelican", "hint": "A large water bird with a long bill" },
    { "word": "stork", "hint": "A tall wading bird with long legs and a long bill" },
    { "word": "heron", "hint": "A long-legged wading bird" },
    { "word": "ibis", "hint": "A wading bird with a long, curved bill" },
    { "word": "crane", "hint": "A tall wading bird with a long neck and legs" },
    { "word": "flamingo", "hint": "A wading bird with pink feathers" },
    { "word": "puffin", "hint": "A seabird with a colorful beak" },
    { "word": "penguin", "hint": "A flightless bird that lives in cold regions" },
    { "word": "emu", "hint": "A large flightless bird native to Australia" },
    { "word": "kiwi", "hint": "A small flightless bird from New Zealand" },
    { "word": "owl", "hint": "A nocturnal bird of prey with large eyes" },
    { "word": "hawk", "hint": "A bird of prey with sharp talons" },
    { "word": "falcon", "hint": "A bird of prey known for its speed" },
    { "word": "eagle", "hint": "A large bird of prey with a hooked beak" },
    { "word": "vulture", "hint": "A scavenging bird of prey" },
    { "word": "parrot", "hint": "A colorful bird known for mimicking sounds" },
    { "word": "bridge", "hint": "A structure built to span a physical obstacle" },
    { "word": "library", "hint": "A place where books are kept" },
    { "word": "museum", "hint": "A building where objects of historical, scientific, or artistic interest are kept" },
    { "word": "restaurant", "hint": "A place where meals are served to customers" },
    { "word": "hospital", "hint": "A place where sick or injured people are treated" },
    { "word": "school", "hint": "A place where children are educated" },
    { "word": "university", "hint": "An institution of higher learning" },
    { "word": "bookstore", "hint": "A place where books are sold" },
    { "word": "bakery", "hint": "A place where bread and cakes are made or sold" },
    { "word": "supermarket", "hint": "A large self-service store selling foods and household goods" },
    { "word": "stadium", "hint": "A large sports arena with tiers of seats" },
    { "word": "airport", "hint": "A place where airplanes take off and land" },
    { "word": "trainstation", "hint": "A place where trains load and unload passengers or goods" },
    { "word": "busstop", "hint": "A place where buses stop to pick up or drop off passengers" },
    { "word": "hotel", "hint": "A place providing accommodation, meals, and other services for travelers" },
    { "word": "cinema", "hint": "A place where movies are shown" },
    { "word": "theater", "hint": "A place where plays and other performances are presented" },
    { "word": "gymnasium", "hint": "A building equipped for indoor sports" },
    { "word": "park", "hint": "A large public green area in a town, used for recreation" },
    { "word": "garden", "hint": "A piece of ground used for growing flowers, fruit, or vegetables" },
    { "word": "market", "hint": "A place where goods are bought and sold" },
    { "word": "church", "hint": "A building used for Christian worship" },
    { "word": "mosque", "hint": "A place of worship for Muslims" },
    { "word": "temple", "hint": "A place of worship in various religions" },
    { "word": "synagogue", "hint": "A Jewish house of worship" },
    { "word": "cathedral", "hint": "The principal church of a diocese" },
    { "word": "bank", "hint": "A financial institution where people deposit money" },
    { "word": "postoffice", "hint": "A place where postal business is conducted" },
    { "word": "court", "hint": "A place where legal cases are heard" },
    { "word": "policestation", "hint": "A building where police officers work" },
    { "word": "firestation", "hint": "A building where firemen wait to be called to a fire" },
    { "word": "factory", "hint": "A building where goods are manufactured" },
    { "word": "warehouse", "hint": "A large building for storing goods" },
    { "word": "office", "hint": "A room where professional duties are performed" },
    { "word": "apartment", "hint": "A suite of rooms forming one residence" },
    { "word": "house", "hint": "A building for human habitation" },
    { "word": "bicycle", "hint": "A two-wheeled vehicle powered by pedaling" },
    { "word": "motorcycle", "hint": "A two-wheeled vehicle powered by an engine" },
    { "word": "car", "hint": "A four-wheeled vehicle for transporting people" },
    { "word": "bus", "hint": "A large vehicle carrying passengers by road" },
    { "word": "truck", "hint": "A large, heavy motor vehicle for transporting goods" },
    { "word": "train", "hint": "A series of connected vehicles traveling on railways" },
    { "word": "ship", "hint": "A large vessel for traveling on water" },
    { "word": "boat", "hint": "A small vessel for traveling on water" },
    { "word": "submarine", "hint": "A watercraft capable of underwater operation" },
    { "word": "rocket", "hint": "A spacecraft launched into space" },
    { "word": "satellite", "hint": "An artificial body placed in orbit around the earth or moon" },
    { "word": "astronaut", "hint": "A person trained to travel in a spacecraft" },
    { "word": "scientist", "hint": "A person who is studying or has expert knowledge of a science" },
    { "word": "doctor", "hint": "A person qualified to practice medicine" },
    { "word": "nurse", "hint": "A person trained to care for the sick" },
    { "word": "teacher", "hint": "A person who teaches, especially in a school" },
    { "word": "student", "hint": "A person who is studying at a school or college" },
    { "word": "engineer", "hint": "A person who designs, builds, or maintains engines, machines, or structures" },
    { "word": "architect", "hint": "A person who designs buildings" },
    { "word": "lawyer", "hint": "A person who practices or studies law" },
    { "word": "judge", "hint": "A public official appointed to decide cases in a court of law" },
    { "word": "pilot", "hint": "A person who operates the flying controls of an aircraft" },
    { "word": "chef", "hint": "A professional cook" },
    { "word": "baker", "hint": "A person who makes bread and cakes" },
    { "word": "butcher", "hint": "A person who sells meat" },
    { "word": "artist", "hint": "A person who creates art" },
    { "word": "musician", "hint": "A person who plays a musical instrument" },
    { "word": "actor", "hint": "A person who performs in plays, movies, or television shows" },
    { "word": "director", "hint": "A person who directs a film or play" },
    { "word": "writer", "hint": "A person who writes books, articles, etc." },
    { "word": "poet", "hint": "A person who writes poems" },
    { "word": "journalist", "hint": "A person who writes for newspapers or magazines" },
    { "word": "photographer", "hint": "A person who takes photographs" },
    { "word": "dentist", "hint": "A person qualified to treat teeth and gums" },
    { "word": "pharmacist", "hint": "A person qualified to prepare and dispense medicinal drugs" },
    { "word": "chemist", "hint": "A scientist who studies the composition of substances" },
    { "word": "biologist", "hint": "A scientist who studies living organisms" },
    { "word": "geologist", "hint": "A scientist who studies the earth" },
    { "word": "meteorologist", "hint": "A scientist who studies the weather" },
    { "word": "physicist", "hint": "A scientist who studies matter and energy" },
    { "word": "astronomer", "hint": "A scientist who studies celestial objects" },
    { "word": "mathematician", "hint": "A person skilled in mathematics" },
    { "word": "historian", "hint": "A person who studies or writes about history" },
    { "word": "philosopher", "hint": "A person engaged in the study of fundamental questions" },
    { "word": "politician", "hint": "A person who is involved in politics" },
    { "word": "president", "hint": "The elected head of a republican state" },
    { "word": "prime minister", "hint": "The head of an elected government" },
    { "word": "governor", "hint": "The elected executive head of a state of the US" },
    { "word": "mayor", "hint": "The elected head of a city, town, or other municipality" },
    { "word": "policeofficer", "hint": "A member of a police force" },
    { "word": "firefighter", "hint": "A person who extinguishes fires" },
    { "word": "soldier", "hint": "A person who serves in an army" },
    { "word": "sailor", "hint": "A person who works as a member of the crew of a ship" },
    { "word": "athlete", "hint": "A person who is proficient in sports" },
    { "word": "coach", "hint": "A person who trains and instructs athletes" },
    { "word": "referee", "hint": "A person who enforces the rules in a sports game" },
    { "word": "umpire", "hint": "An official in a sport who enforces the rules" },
    { "word": "judge", "hint": "A person who decides the results of a competition" },
    { "word": "dancer", "hint": "A person who dances" },
    { "word": "singer", "hint": "A person who sings" },
    { "word": "painter", "hint": "A person who paints pictures" },
    { "word": "mountain", "hint": "A large natural elevation of the earth's surface" },
    { "word": "ocean", "hint": "A vast body of salt water covering most of the earth" },
    { "word": "river", "hint": "A large natural stream of water flowing in a channel" },
    { "word": "valley", "hint": "A low area between hills or mountains" },
    { "word": "forest", "hint": "A large area covered chiefly with trees and undergrowth" },
    { "word": "desert", "hint": "A barren area of landscape with little rainfall" },
    { "word": "island", "hint": "A piece of land surrounded by water" },
    { "word": "continent", "hint": "One of the earth's large landmasses" },
    { "word": "country", "hint": "A nation with its own government" },
    { "word": "city", "hint": "A large town" },
    { "word": "village", "hint": "A small settlement" },
    { "word": "town", "hint": "An urban area that is smaller than a city" },
    { "word": "capital", "hint": "The city where a country's government is located" },
    { "word": "district", "hint": "An area of a country or city" },
    { "word": "neighborhood", "hint": "A district, especially one forming a community within a town or city" },
    { "word": "avenue", "hint": "A broad road in a town or city" },
    { "word": "street", "hint": "A public road in a city or town" },
    { "word": "road", "hint": "A wide way leading from one place to another" },
    { "word": "highway", "hint": "A main road, especially one connecting major towns or cities" },
    { "word": "path", "hint": "A way or track laid down for walking or made by continual treading" },
    { "word": "bridge", "hint": "A structure built to span a physical obstacle" },
    { "word": "tunnel", "hint": "An artificial underground passage" },
    { "word": "park", "hint": "A large public green area in a town, used for recreation" },
    { "word": "square", "hint": "An open, typically four-sided, area surrounded by buildings in a town" },
    { "word": "garden", "hint": "A piece of ground used for growing flowers, fruit, or vegetables" },
    { "word": "museum", "hint": "A building where objects of historical, scientific, or artistic interest are kept" },
    { "word": "library", "hint": "A place where books are kept" },
    { "word": "school", "hint": "A place where children are educated" },
    { "word": "university", "hint": "An institution of higher learning" },
    { "word": "hospital", "hint": "A place where sick or injured people are treated" },
    { "word": "clinic", "hint": "A place or hospital department where outpatients are given medical treatment" },
    { "word": "pharmacy", "hint": "A store where medicinal drugs are dispensed and sold" },
    { "word": "shop", "hint": "A place where goods are sold" },
    { "word": "supermarket", "hint": "A large self-service store selling foods and household goods" },
    { "word": "bakery", "hint": "A place where bread and cakes are made or sold" },
    { "word": "butcher", "hint": "A shop where meat is sold" },
    { "word": "restaurant", "hint": "A place where meals are served to customers" },
    { "word": "cafe", "hint": "A small restaurant selling light meals and drinks" },
    { "word": "bar", "hint": "A place where alcoholic drinks are served" },
    { "word": "hotel", "hint": "A place providing accommodation, meals, and other services for travelers" },
    { "word": "motel", "hint": "A roadside hotel designed primarily for motorists" },
    { "word": "theater", "hint": "A place where plays and other performances are presented" },
    { "word": "cinema", "hint": "A place where movies are shown" },
    { "word": "stadium", "hint": "A large sports arena with tiers of seats" },
    { "word": "gymnasium", "hint": "A building equipped for indoor sports" },
    { "word": "pool", "hint": "A small area of still water, typically one formed naturally" },
    { "word": "airport", "hint": "A place where airplanes take off and land" },
    { "word": "station", "hint": "A regular stopping place on a public transportation route" },
    { "word": "harbor", "hint": "A place on the coast where vessels may find shelter" },
    { "word": "port", "hint": "A town or city with a harbor where ships load or unload" },
    { "word": "factory", "hint": "A building where goods are manufactured" },
    { "word": "warehouse", "hint": "A large building for storing goods" },
    { "word": "office", "hint": "A room where professional duties are performed" },
    { "word": "studio", "hint": "A room where an artist, photographer, sculptor, etc., works" },
    { "word": "laboratory", "hint": "A room or building equipped for scientific experiments" },
    { "word": "workshop", "hint": "A room or building in which goods are manufactured or repaired" },
    { "word": "garage", "hint": "A building for housing a motor vehicle" },
    { "word": "barn", "hint": "A large farm building used for storing grain, hay, or straw" },
    { "word": "silo", "hint": "A tall tower used for storing grain" },
    { "word": "warehouse", "hint": "A large building where raw materials or manufactured goods are stored" },
    { "word": "skyscraper", "hint": "A very tall building" },
    { "word": "temple", "hint": "A building devoted to the worship of a god or gods" },
    { "word": "church", "hint": "A building used for Christian worship" },
    { "word": "mosque", "hint": "A place of worship for Muslims" },
    { "word": "synagogue", "hint": "A Jewish house of worship" },
    { "word": "monument", "hint": "A structure erected to commemorate persons or events" },
    { "word": "fountain", "hint": "A decorative structure that sends a stream of water into the air" },
    { "word": "statue", "hint": "A carved or cast figure of a person or animal" },
    { "word": "sculpture", "hint": "The art of making two- or three-dimensional representative or abstract forms" },
    { "word": "gallery", "hint": "A room or building for the display or sale of works of art" },
    { "word": "exhibit", "hint": "A display or demonstration of a particular skill" },
    { "word": "aquarium", "hint": "A tank of water where fish and other aquatic animals are kept" },
    { "word": "zoo", "hint": "A facility with enclosures to house animals for public viewing" },
    { "word": "playground", "hint": "An outdoor area where children can play" },
    { "word": "amusementpark", "hint": "A large outdoor area with fairground rides, shows, and other entertainments" },
    { "word": "marketplace", "hint": "An open space where a market is held" },
    { "word": "shoppingmall", "hint": "A large building or series of connected buildings containing a variety of retail stores" },
    { "word": "bazaar", "hint": "A market in a Middle Eastern country" },
    { "word": "fair", "hint": "A gathering of stalls and amusements for public entertainment" },
    { "word": "festival", "hint": "A day or period of celebration, typically for religious reasons" },
    { "word": "concert", "hint": "A musical performance given in public" },
    { "word": "conference", "hint": "A formal meeting for discussion" },
    { "word": "seminar", "hint": "A conference or other meeting for discussion or training" },
    { "word": "workshop", "hint": "A meeting at which a group engages in intensive discussion and activity on a particular subject" },
    { "word": "lecture", "hint": "An educational talk to an audience" },
    { "word": "meeting", "hint": "An assembly of people for a particular purpose" },
    { "word": "ceremony", "hint": "A formal event held on important social or religious occasions" },
    { "word": "wedding", "hint": "A marriage ceremony, especially considered as including the associated celebrations" },
    { "word": "funeral", "hint": "A ceremony honoring someone who has recently died" },
    { "word": "celebration", "hint": "The action of marking one's pleasure at an important event or occasion by engaging in enjoyable, typically social, activity" },
    { "word": "party", "hint": "A social gathering of invited guests, typically involving eating, drinking, and entertainment" },
    { "word": "keyboard", "hint": "A panel of keys that operate a computer or typewriter" },
    { "word": "monitor", "hint": "A screen used to display output from a computer" },
    { "word": "mouse", "hint": "A hand-held device used to control a cursor on a computer screen" },
    { "word": "printer", "hint": "A machine for printing text or pictures" },
    { "word": "router", "hint": "A device that forwards data packets between computer networks" },
    { "word": "server", "hint": "A computer that provides data to other computers" },
    { "word": "software", "hint": "Programs and other operating information used by a computer" },
    { "word": "hardware", "hint": "The physical parts of a computer system" },
    { "word": "application", "hint": "A program or piece of software designed to fulfill a particular purpose" },
    { "word": "database", "hint": "An organized collection of data" },
    { "word": "algorithm", "hint": "A process or set of rules followed in calculations or problem-solving" },
    { "word": "network", "hint": "A group of interconnected computers" },
    { "word": "encryption", "hint": "The process of converting information into a code to prevent unauthorized access" },
    { "word": "firewall", "hint": "A security system that controls incoming and outgoing network traffic" },
    { "word": "password", "hint": "A secret word or phrase used for authentication" },
    { "word": "username", "hint": "An identification used by a person to access a computer or network" },
    { "word": "cloud", "hint": "Remote servers that store data accessible over the internet" },
    { "word": "browser", "hint": "A software application for accessing information on the World Wide Web" },
    { "word": "email", "hint": "Electronic mail" },
    { "word": "attachment", "hint": "A file sent along with an email" },
    { "word": "spam", "hint": "Unwanted or junk email" },
    { "word": "phishing", "hint": "Fraudulent attempts to obtain sensitive information via email" },
    { "word": "malware", "hint": "Software designed to disrupt or damage a computer system" },
    { "word": "virus", "hint": "A malicious program that can replicate itself and spread to other computers" },
    { "word": "trojan", "hint": "A type of malware disguised as legitimate software" },
    { "word": "worm", "hint": "A self-replicating program that spreads to other computers" },
    { "word": "spyware", "hint": "Software that secretly monitors and collects information about a user" },
    { "word": "adware", "hint": "Software that displays unwanted advertisements" },
    { "word": "ransomware", "hint": "Malware that encrypts a user's data and demands payment for its release" },
    { "word": "backup", "hint": "A copy of data kept for protection against loss" },
    { "word": "restore", "hint": "The process of returning data to its original state" },
    { "word": "update", "hint": "A new version or improvement of software" },
    { "word": "upgrade", "hint": "An improvement or enhancement of hardware or software" },
    { "word": "download", "hint": "To transfer data from the internet to a local computer" },
    { "word": "upload", "hint": "To transfer data from a local computer to the internet" },
    { "word": "streaming", "hint": "Playing video or audio content without downloading the file" },
    { "word": "bandwidth", "hint": "The amount of data that can be transmitted over a network in a given time" },
    { "word": "latency", "hint": "The delay before a transfer of data begins following an instruction" },
    { "word": "cache", "hint": "A storage location that retains frequently accessed data for quick access" },
    { "word": "cookie", "hint": "A small piece of data stored on a user's computer by a web browser" },
    { "word": "IP address", "hint": "A unique string of numbers that identifies each computer using the Internet Protocol" },
    { "word": "domain", "hint": "The name of a website" },
    { "word": "URL", "hint": "Uniform Resource Locator, the address of a web page" },
    { "word": "DNS", "hint": "Domain Name System, translates domain names to IP addresses" },
    { "word": "protocol", "hint": "A set of rules governing data communication" },
    { "word": "HTML", "hint": "Hypertext Markup Language, the standard language for web pages" },
    { "word": "CSS", "hint": "Cascading Style Sheets, used for styling web pages" },
    { "word": "JavaScript", "hint": "A programming language commonly used to create interactive effects within web browsers" },
    { "word": "Python", "hint": "A high-level programming language known for its readability" },
    { "word": "Java", "hint": "A high-level programming language used to create applications for web, mobile, and desktop" },
    { "word": "C++", "hint": "A high-level programming language with object-oriented features" },
    { "word": "Ruby", "hint": "A dynamic, open-source programming language with a focus on simplicity and productivity" },
    { "word": "PHP", "hint": "A scripting language especially suited to web development" },
    { "word": "SQL", "hint": "Structured Query Language, used for managing databases" },
    { "word": "JSON", "hint": "JavaScript Object Notation, a lightweight data interchange format" },
    { "word": "XML", "hint": "eXtensible Markup Language, used to define rules for encoding documents" },
    { "word": "API", "hint": "Application Programming Interface, a set of tools for building software applications" },
    { "word": "SDK", "hint": "Software Development Kit, a collection of software tools and libraries" },
    { "word": "IDE", "hint": "Integrated Development Environment, a software application for software development" },
    { "word": "repository", "hint": "A central location where data is stored and managed" },
    { "word": "version", "hint": "A specific form of a software or application" },
    { "word": "debugging", "hint": "The process of identifying and removing errors from software" },
    { "word": "compiling", "hint": "The process of converting source code into executable code" },
    { "word": "syntax", "hint": "The set of rules that define the combinations of symbols that are considered to be correctly structured programs in a programming language" },
    { "word": "variable", "hint": "A storage location identified by a name that holds data" },
    { "word": "function", "hint": "A block of code designed to perform a particular task" },
    { "word": "loop", "hint": "A sequence of instructions that repeats until a certain condition is met" },
    { "word": "conditional", "hint": "Statements that only run when a specified condition is true" },
    { "word": "array", "hint": "A collection of elements identified by an index" },
    { "word": "object", "hint": "An instance of a class containing data and behavior" },
    { "word": "class", "hint": "A blueprint for creating objects" },
    { "word": "inheritance", "hint": "A mechanism by which one class acquires the properties of another class" },
    { "word": "polymorphism", "hint": "The ability to process objects differently based on their data type or class" },
    { "word": "encapsulation", "hint": "The bundling of data with the methods that operate on that data" },
    { "word": "abstraction", "hint": "The concept of hiding the complex implementation details and showing only the essential features" },
    { "word": "framework", "hint": "A platform for developing software applications" },
    { "word": "library", "hint": "A collection of precompiled routines that a program can use" },
    { "word": "module", "hint": "A self-contained unit of code" },
    { "word": "package", "hint": "A collection of modules" },
    { "word": "dependency", "hint": "A piece of software that another piece of software relies on" },
    { "word": "script", "hint": "A file containing code that is executed by an interpreter" },
    { "word": "compiler", "hint": "A program that translates source code into executable code" },
    { "word": "interpreter", "hint": "A program that directly executes instructions written in a programming language" },
    { "word": "virtual machine", "hint": "A software emulation of a physical computer" },
    { "word": "container", "hint": "A lightweight, standalone, and executable software package" },
    { "word": "microservice", "hint": "A small, autonomous service that works together with other services" },
    { "word": "orchestration", "hint": "Automated configuration, coordination, and management of computer systems and software" },
    { "word": "pencil", "hint": "A writing instrument made of graphite and wood" },
    { "word": "eraser", "hint": "A tool used to remove pencil marks" },
    { "word": "notebook", "hint": "A book with blank pages for writing notes" },
    { "word": "paper", "hint": "A material used for writing or printing on" },
    { "word": "book", "hint": "A set of written, printed, or blank pages fastened together" },
    { "word": "magazine", "hint": "A periodical publication containing articles and illustrations" },
    { "word": "newspaper", "hint": "A printed publication with news, articles, and advertisements" },
    { "word": "calendar", "hint": "A system of organizing days for social, religious, or commercial purposes" },
    { "word": "clock", "hint": "A device for measuring and displaying time" },
    { "word": "watch", "hint": "A small timepiece worn typically on a strap on one's wrist" },
    { "word": "lamp", "hint": "A device that produces light" },
    { "word": "couch", "hint": "A piece of furniture for seating multiple people" },
    { "word": "chair", "hint": "A piece of furniture for one person to sit on" },
    { "word": "table", "hint": "A piece of furniture with a flat top and one or more legs" },
    { "word": "desk", "hint": "A piece of furniture with a flat top used for writing or working" },
    { "word": "shelf", "hint": "A flat board used to hold items" },
    { "word": "cupboard", "hint": "A cabinet with shelves for storing dishes, food, or other items" },
    { "word": "bed", "hint": "A piece of furniture for sleeping on" },
    { "word": "pillow", "hint": "A soft support for the head while sleeping" },
    { "word": "blanket", "hint": "A large piece of cloth used to keep warm" },
    { "word": "wardrobe", "hint": "A tall cabinet for storing clothes" },
    { "word": "mirror", "hint": "A reflective surface, typically of glass coated with a metal amalgam" },
    { "word": "rug", "hint": "A piece of thick fabric for covering part of a floor" },
    { "word": "carpet", "hint": "A floor covering made from thick woven fabric" },
    { "word": "curtain", "hint": "A piece of cloth that hangs down from above a window" },
    { "word": "shower", "hint": "A device that sprays water for washing the body" },
    { "word": "bathtub", "hint": "A large container for holding water in which a person may bathe" },
    { "word": "sink", "hint": "A basin for washing in the kitchen or bathroom" },
    { "word": "stove", "hint": "A kitchen appliance used for cooking" },
    { "word": "oven", "hint": "A chamber used for baking or roasting food" },
    { "word": "microwave", "hint": "An appliance that cooks food using microwaves" },
    { "word": "toaster", "hint": "A small appliance that browns slices of bread" },
    { "word": "fridge", "hint": "An appliance for keeping food and drinks cold" },
    { "word": "freezer", "hint": "A device used to store food at very low temperatures" },
    { "word": "blender", "hint": "An appliance for mixing and blending foods" },
    { "word": "dishwasher", "hint": "A machine for washing dishes automatically" },
    { "word": "washingmachine", "hint": "An appliance for washing clothes automatically" },
    { "word": "dryer", "hint": "An appliance for drying clothes" },
    { "word": "iron", "hint": "A device for smoothing or pressing clothes" },
    { "word": "vacuum", "hint": "A machine that cleans floors by suction" },
    { "word": "broom", "hint": "A tool for sweeping floors" },
    { "word": "mop", "hint": "A tool for cleaning floors with water" }
]
